import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarDemo } from "@/components/navbar";
import Logo from "@/components/logo";
import Bot from "@/components/bot";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarDemo>
         <Logo></Logo>
         <div className="flex justify-end items-end w-full mr-72">
            <Bot />
          </div>

          {children}

        </SidebarDemo>
        </body>
    </html>
  );
}
